feat: adds ability to share fragments across components
data-eden/data-eden pull request #106
Opened 2023-05-15 05:03 UTC by gabrielcsapo

- fixes: getDefinition to throw an error that showcases the location of the error
- chore: updates implementation for codegen in the readme
- feat: enables the ability to import fragments from compnents and use them in queries
- chore: adds test to validate sharing fragments between components
- chore: adds a test that validates sharing fragments between components nested

2023-05-15 16:10 UTC, gabrielcsapo commented on internal-packages/react-graphql-test-app/package.json
> +    "codegen": "athena-codegen --schema-path schema.graphql --base-dir src/graphql --documents **/*.graphql **/**/*.tsx"
yeah so if we have one depth it will only do two files, if we add the extended globbing pattern we get all of them.

2023-05-15 16:11 UTC, gabrielcsapo commented on packages/codegen/__tests__/codegen.test.ts
> +
yeah I think we need to deduplicate as we have userFieldFragment in two components that are in the import chain.

2023-05-15 16:25 UTC, gabrielcsapo commented on fixes.md
deleting this.

2023-05-15 16:43 UTC, hjdivad requested changes

2023-05-15 16:43 UTC, hjdivad commented on packages/codegen/__tests__/codegen.test.ts
> +  test.only('with gql tags', async () => {
silly @hjdivad

2023-05-15 16:43 UTC, hjdivad commented on packages/codegen/__tests__/codegen.test.ts
> +      export const UserFieldsFragmentDoc = {\\"kind\\":\\"Document\\",\\"definitions\\":[{\\"kind\\":\\"FragmentDefinition\\",\\"name\\":{\\"kind\\":\\"Name\\",\\"value\\":\\"UserFields\\"},\\"typeCo
🐛 don't export the fragment docs at all, either dev or test

2023-05-15 16:43 UTC, hjdivad commented on packages/codegen/__tests__/codegen.test.ts
> +      export type MessageFieldsFragment = { __typename: 'ChatMessage', id: string, content: string, time: any };
🐛  chatview should not export the type `MessageFieldsFragment` -- it should only export the fragment types that it defines itself.

2023-05-17 01:24 UTC, merged

2023-05-18 21:41 UTC, gabrielcsapo commented
- fixes: getDefinition to throw an error that showcases the location of the error
- chore: updates implementation for codegen in the readme
- feat: enables the ability to import fragments from compnents and use them in queries
- chore: adds test to validate sharing fragments between components
- chore: adds a test that validates sharing fragments between components nested
- fix(bug): properly thread through filename to getDefinition as documentNode does not
 maintain ownership
- feat: adds cli logging when complete
- fix(bug): ensure we do not include duplicate types that are exported
- fix: double fragment exports